### Numpy  - Numerical Python

In [158]:
import numpy as np
my_list = [1,2,3,4,5]
numpy_array = np.array(my_list)
print("Simple Numpy array:",numpy_array)

Simple Numpy array: [1 2 3 4 5]


In [160]:
zero_array = np.zeros((2,3))  # Creates an array filled with zeros.
print("Zero array:","\n",zero_array)

ones_array = np.ones((3,3))       # Creates an array filled with ones.
print("\n","ones array:","\n",ones_array)

constant_array = np.full((2,2),7)     # Creates an array filled with specific values.
print("\n","Constant array","\n",constant_array)

range_array =np.arange(0,10,2) #Start stop step
print("\n","range_array","\n",range_array)      # Creates an array filled with evenly spaced 

linspace_array = np.linspace(0,1,5)  # Start stop 
print("\n","linespace_array","\n",linspace_array)  # Creates an array filled with evenly spaced in interval 


Zero array: 
 [[0. 0. 0.]
 [0. 0. 0.]]

 ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

 Constant array 
 [[7 7]
 [7 7]]

 range_array 
 [0 2 4 6 8]

 linespace_array 
 [0.   0.25 0.5  0.75 1.  ]


In [162]:
# random_rand - Creates array of specific shape & fills it with random values with uniform dist 

random_array = np.random.rand(2,3)
random_array

array([[0.48309517, 0.3598069 , 0.8209728 ],
       [0.19114836, 0.27392312, 0.8820155 ]])

In [164]:
# random_randn = Creates array of specific shape & fills it with random variables with nprma; dist.

normal_array = np.random.randn(2,2)
normal_array

array([[ 1.10409413,  1.25315611],
       [ 1.24491035, -0.83390044]])

In [166]:
# randint_array = Creates array of specific shape & fills it with random integers

randint_array = np.random.randint(1,10,size = (2,3))
randint_array

array([[6, 6, 8],
       [8, 7, 6]])

### Convert Python list into Numpy Arrays

In [169]:
a = [1,2,3,4,5]

arr = np.array(a)
print(arr)
arr

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [171]:
a = [1.2,2.6,3.3,4.2]
arr = np.array(a)
print(arr)
arr

[1.2 2.6 3.3 4.2]


array([1.2, 2.6, 3.3, 4.2])

In [173]:
a = [1,2,3,4]
arr = np.asarray(a)
print(arr)
arr

[1 2 3 4]


array([1, 2, 3, 4])

### Specifying Data Types in NumPy Arrays


In [219]:
a = [1.5,2.8,3.1]
arr = np.array(a,dtype = int)
print(arr)

[1 2 3]


### Nested Lists to Numpy arrays

In [179]:
a = [[1,2,3],[4,5,6],[7,8,9]]  

# Convert to a 2D NumPy array
arr = np.array(a)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Reshaping NumPy Arrays


In [194]:
a = [1,2,3,4,5,6]
arr = np.array(a)
print(arr.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


### Combining Multiple Lists into a NumPy Array


In [211]:
a = [1, 2, 3]
b = [4, 5, 6]
c = [7, 8, 9]

# Combine lists into a single NumPy array
arr = np.array([a,b,c])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [221]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr[0])

10


In [243]:
# 2D Arrays
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix[1,2]

6

In [247]:
# 3D Arrays
cube = np.array( [[[1,2,3],[4,5,6],[7,8,9]],
                   [[10,11,12],[13,14,15],[16,17,18]]])

print(cube[1,2,0])  # Depth - Row - Column

16


In [249]:
print(cube)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


### Slicing Arrays

In [256]:
arr = np.array([0,1,2,3,4,5])
print(arr[1:4])

[1 2 3]


In [276]:
# Slicing Multidimensional Arrays:-
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [282]:
print(matrix[0:2,1:3])

[[2 3]
 [5 6]]


In [290]:
# Modifying Array Elements

arr = np.array([1,2,3,4])
arr[1:3] = 99
print(arr)

[ 1 99 99  4]


In [299]:
# Ellipsis (...) in Indexing

cube = np.random.rand(4, 4, 4)
print(cube[...,0])


[[0.97986669 0.85546429 0.17704051 0.24333104]
 [0.23798059 0.14151516 0.63027898 0.13665176]
 [0.03778463 0.23983071 0.72153785 0.04795541]
 [0.82023532 0.04841772 0.32874879 0.01553083]]


In [303]:
# Fancy Indexing

arr = np.array([10,20,30,40,50])
indices = [0,2,4]
print(arr[indices])

[10 30 50]


### How to access different rows of a multidimensional NumPy array?

In [322]:
arr = np.array([[10,20,30],
               [40,5,66],
               [70,88,94]])

print("Given Array:")
print(arr)

# Access the First & last rows of array
res_arr = arr[[0,2]]
print("\nAccessed Rows:")
print(res_arr)

Given Array:
[[10 20 30]
 [40  5 66]
 [70 88 94]]

Accessed Rows:
[[10 20 30]
 [70 88 94]]


In [342]:
# Accessing the Middle row of 2-D NumPy array
arr = np.array([[101,20,3,10],
               [40,5,66,7],
               [70,88,9,141]
               ])
print("Given array :")
print(arr)

# Access the Middle row of array
res_arr = arr[1]
print("\n Accessed row:")
print(res_arr)

Given array :
[[101  20   3  10]
 [ 40   5  66   7]
 [ 70  88   9 141]]

 Accessed row:
[40  5 66  7]


In [354]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])
print("Re-shaping Size :")
print(array.reshape(8,2))

Re-shaping Size :
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]


In [366]:
a1 = np.array([1,2,3])
a2 = np.array([2,3,4])
net = a1+a2
net1 = a1-a2
net2 = a1*a2
print(net)
print(net1)
print(net2)

[3 5 7]
[-1 -1 -1]
[ 2  6 12]


### Numpy stack() in Python

In [375]:
a = np.array([1,2,3])
b = np.array([4,5,6])

#Stacking - 
c = np.stack((a,b),axis = 0) # axis = 0 means row, axis = 1 means column
print(c)

[[1 2 3]
 [4 5 6]]


In [383]:
d = np.stack((a,b),axis = -1)
print(d)

[[1 4]
 [2 5]
 [3 6]]


In [387]:
# stacking two 2d arrays
# input arrays
x=np.array([[1,2,3],
            [4,5,6]])

y=np.array([[7,8,9],
            [10,11,12]])

In [389]:
np.stack((x,y),axis = 0)   ## ROW stack

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [393]:
np.stack((x,y),axis = 1) ## Column stack

array([[[ 1,  2,  3],
        [ 7,  8,  9]],

       [[ 4,  5,  6],
        [10, 11, 12]]])

### Spliting in Numpy

In [405]:
Arr = np.array([1,2,3,4,5,6])
array = np.array_split(arr,3)
print(array)

[array([[101,  20,   3,  10]]), array([[40,  5, 66,  7]]), array([[ 70,  88,   9, 141]])]


In [407]:
Arr = np.array([1,2,3,4,5,6])
array = np.array_split(arr,2)
print(array)

[array([[101,  20,   3,  10],
       [ 40,   5,  66,   7]]), array([[ 70,  88,   9, 141]])]


In [415]:
array = np.arange(6)
array                

array([0, 1, 2, 3, 4, 5])

In [419]:
## Spliting array into 2 equal parts

result = np.split(array,2)
result

[array([0, 1, 2]), array([3, 4, 5])]

In [429]:
result1 = np.arange(16)
np.split(result1,4)

[array([0, 1, 2, 3]),
 array([4, 5, 6, 7]),
 array([ 8,  9, 10, 11]),
 array([12, 13, 14, 15])]

In [442]:
# Vertical spliting
matrix = np.array([[1,2,3],
                         [4,5,6],
                             [7,8,9],
                                  [10,11,12]])

In [444]:
np.vsplit(matrix,2)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

In [458]:
# Horizontal spliting
matrix = np.array([[1,2,3],
                         [4,5,6]])
                             
np.hsplit(matrix,1)

[array([[1, 2, 3],
        [4, 5, 6]])]

### Numpy Array Broadcasting

In [491]:
'''Broadcasting in NumPy allows us to perform arithmetic
operations on arrays of different shapes without reshaping them'''

array_2d = np.array([[1,2,3],[4,5,6]])  
scaler = 10

result = array_2d +scaler
print(result)

[[11 12 13]
 [14 15 16]]


In [493]:
# 2-D array
a1 = np.array([2,4,6])
a2 = np.array([[1,3,5],[7,9,11]])
res = a1+a2
print(res)

[[ 3  7 11]
 [ 9 13 17]]


In [500]:
# Broadcasting in conditional operator

ages = np.array([12,24,35,45,60,72])
age_group = np.array(["Adult","Minor"])
result = np.where(ages>18,age_group[0],age_group[1])
print(result)

['Minor' 'Adult' 'Adult' 'Adult' 'Adult' 'Adult']


### NumPy - Arithmetic Operations

In [504]:
# Addition of Arrays

a = np.array([5,72,13,100])
b = np.array([2,5,10,30])

add_ans = np.add(a,b)
print(add_ans)

[  7  77  23 130]


In [508]:
# Subtraction of Arrays

subs_ans = np.subtract(a,b)
print(subs_ans)

[ 3 67  3 70]


In [514]:
# Multiplication of Arrays

mul_ans = np.multiply(a,b)
print(mul_ans)

[  10  360  130 3000]


In [520]:
# Division of Arrays

div_ans = np.divide(a,b)
print(div_ans)

[ 2.5        14.4         1.3         3.33333333]


In [524]:
pow_ans = np.power(a,b)
pow_ans

array([                 25,          1934917632,        137858491849,
       1152921504606846976])

In [528]:
pow_ans = np.mod(a,b)
pow_ans

array([ 1,  2,  3, 10])